export const FeedbackOverlayKind = Object.freeze({
  EMPTY_BALANCE: 'EMPTY_BALANCE',
  CHECK_EMAIL_TO_CONFIRM_WITHDRAWAL_ADDRESS: 'CHECK_EMAIL_TO_CONFIRM_WITHDRAWAL_ADDRESS',
  SENT_BTC_FOLLOW_ON_BLOCKCHAIN: 'SENT_BTC_FOLLOW_ON_BLOCKCHAIN',
  DEPOSIT_COMPLETED: 'DEPOSIT_COMPLETED',
  CHAMPION_ANNOUNCEMENT: 'CHAMPION_ANNOUNCEMENT',
  BALANCE_TO_SEND: 'BALANCE_TO_SEND',
});
